# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d280b462333733adc644d48be0cfa12dff33b6d2dda8910550cfdeebb9a65387bd1b7383e111aee78519f3fe6fcb8723720c2ba414907c15197dd9c4373382e

test:
  secret_key_base: bb7a09504a09f75aebc2c11c853c9e601698c037b977fb9cc65844cbc37ef0b4ac1e7357748b16e2e4615b8906c5b12302b9aba465d4b3c37f6298d549e3a472

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
